name: gogoeat CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:

  ## 3
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Access MAP_API_KEY
        env:
          MAP_KEY: ${{ secrets.MAP_API_KEY }}
        run: echo MAP_API_KEY=\"$MAP_KEY\" > ./local.propertie
        
      - name: Unit tests
        run: ./gradlew test
  ## 4
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Access MAP_API_KEY
        env:
          MAP_KEY: ${{ secrets.MAP_API_KEY }}
        run: echo MAP_API_KEY=\"$MAP_KEY\" > ./local.propertie

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTes
