name: gogoeat CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:

  ## 3
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Access MAP_API_KEY
        env:
          MAP_KEY: ${{ secrets.MAP_API_KEY }}
        run: echo "MAP_API_KEY=\""${{ secrets.MAP_API_KEY }}"\"" >> local.properties
        
      - name: Unit tests
        run: ./gradlew test
  ## 4
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Access MAP_API_KEY
        run: echo "MAP_API_KEY=\""${{ secrets.MAP_API_KEY }}"\"" >> local.properties

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTes
          
  build:
    needs: [ unit_tests, android_tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Access MAP_API_KEY
        run: echo "MAP_API_KEY=\""${{ secrets.MAP_API_KEY }}"\"" >> local.properties
        
      - name: Generate Release APK
        run: ./gradlew assembleRelease
