name: gogoeat CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
      
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Access MAP_API_KEY
        env:
          MAP_KEY: ${{ secrets.MAP_API_KEY }}
        run: echo MAP_API_KEY=\"$MAP_KEY\" > ./local.propertie

      - name: Unit tests
        run: bash ./gradlew test --stacktrace
        
  debug:
    name: Generate Debug APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Access MAP_API_KEY
        env:
          MAP_KEY: ${{ secrets.MAP_API_KEY }}
        run: echo MAP_API_KEY=\"$MAP_KEY\" > ./local.propertie
        
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
