name: gogoeat CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      needToPublish:
        type: choice
        required: true
        default: 'false'
        options:
          - true
          - false

jobs:

  ## 1
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Access LOCAL_PROPERTIES
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > local.properties
        
      - name: Access Android signing key JKS
        run: |
          echo "${{ secrets.RELEASE_KEY_STORE_64 }}" > app/sam_google_play_keys.jks.base64
          base64 -d app/sam_google_play_keys.jks.base64 > app/sam_google_play_keys.jks

      - name: Access Google Services Json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > app/google-services.json
        
      - name: Unit tests
        run: ./gradlew test
  ## 2
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Access LOCAL_PROPERTIES
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > local.properties
        
      - name: Access Android signing key JKS
        run: |
          echo "${{ secrets.RELEASE_KEY_STORE_64 }}" > app/sam_google_play_keys.jks.base64
          base64 -d app/sam_google_play_keys.jks.base64 > app/sam_google_play_keys.jks

      - name: Access Google Services Json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > app/google-services.json

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTes
  ## 3
  build:
    needs: [ unit_tests, android_tests ]
    if: ${{ github.event.inputs.needToPublish == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Access LOCAL_PROPERTIES
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > local.properties
        
      - name: Access Android signing key JKS
        run: |
          echo "${{ secrets.RELEASE_KEY_STORE_64 }}" > app/sam_google_play_keys.jks.base64
          base64 -d app/sam_google_play_keys.jks.base64 > app/sam_google_play_keys.jks

      - name: Access Google Services Json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > app/google-services.json
        
      - name: Generate Release APK
        run: ./gradlew assembleRelease
